SELECT * FROM TravelSchedule;
SELECT * FROM CITY;
--------------------------------용훈-----------------------------------------



--------------------------------범식-----------------------------------------
SELECT * FROM HOTEL;



--------------------------------도영-----------------------------------------

SELECT * FROM TRAVELSCHEDULE;
SELECT * FROM TWTMEMBER;
SELECT * FROM SCHEDULEREVIEW;
SELECT * FROM TRAVELPOINT;
		SELECT * FROM TRAVELSCHEDULE TS LEFT JOIN TWTMEMBER M ON (TS.M_CODE = M.M_CODE) LEFT JOIN TRAVELSCHEDULE_DAY TD ON (TS.TS_CODE = TD.TS_CODE) LEFT JOIN TRAVELPOINT TP ON(TS.TP_CODE = TP.TP_CODE) ORDER BY TS_DATE DESC
SELECT * FROM TRAVELSCHEDULE_DAY;
SELECT * FROM TRAVELSCHEDULE TS LEFT JOIN TWTMEMBER M ON (TS.M_CODE = M.M_CODE)
SELECT * FROM TRAVELSCHEDULE TS LEFT JOIN TWTMEMBER M ON (TS.M_CODE = M.M_CODE) LEFT JOIN TRAVELSCHEDULE_DAY TD ON (TS.TS_CODE = TD.TS_CODE) LEFT JOIN TRAVELPOINT TP ON(TS.TP_CODE = TP.TP_CODE) WHERE TS.TS_THEME = '여행테마' ORDER BY TS_DATE DESC
INSERT INTO "TRAVELSCHEDULE_DAY" (TS_DAY, TS_CODE, TP_CODE, TS_MEMO, TS_MONEY) VALUES ('DAY1', 'TS1', 'TP1', '여행메모', 30000);
INSERT INTO "TRAVELSCHEDULE_DAY" (TS_DAY, TS_CODE, TP_CODE, TS_MEMO, TS_MONEY) VALUES ('DAY2', 'TS1', 'TP100', '여행메모', 30000);
DELETE FROM TRAVELSCHEDULE_DAY WHERE TP_CODE = 'TP'
		SELECT * FROM TRAVELSCHEDULE TS LEFT JOIN TWTMEMBER M ON (TS.M_CODE = M.M_CODE) LEFT JOIN TRAVELSCHEDULE_DAY TD ON (TS.TS_CODE = TD.TS_CODE) LEFT JOIN TRAVELPOINT TP ON(TS.TP_CODE = TP.TP_CODE) WHERE TS.TS_CODE = 'TS1'
		SELECT TS.TS_CODE, TS.M_CODE, TS.TP_CODE, TS.TS_TITLE, TS.TS_SDAY, TS.TS_THEME, TS.TS_PEOPLE, TS.TS_THUM, TS.TS_PERIOD, TS.TS_DATE, TS.TS_VIEW, M.M_NAME, TP.CITY_CODE, TP.TP_IMG FROM TRAVELSCHEDULE TS LEFT JOIN TWTMEMBER M ON (TS.M_CODE = M.M_CODE) LEFT JOIN TRAVELPOINT TP ON(TS.TP_CODE = TP.TP_CODE) ORDER BY TS_DATE DESC
SELECT TS.TS_CODE, TS.M_CODE, TS.TP_CODE, TS.TS_TITLE, TS.TS_SDAY, TS.TS_THEME, TS.TS_PEOPLE, TS.TS_THUM, TS.TS_DATE, TS.TS_VIEW, M.M_NAME, TP.CITY_CODE, TP.TP_IMG FROM TRAVELSCHEDULE TS LEFT JOIN TWTMEMBER M ON (TS.M_CODE = M.M_CODE) LEFT JOIN TRAVELSCHEDULE_DAY TD ON (TS.TS_CODE = TD.TS_CODE) LEFT JOIN TRAVELPOINT TP ON(TS.TP_CODE = TP.TP_CODE) WHERE TS.TS_CODE = 'TS4'

// 디테일리스트
SELECT * FROM TRAVELSCHEDULE TS LEFT JOIN TWTMEMBER M ON (TS.M_CODE = M.M_CODE) LEFT JOIN TRAVELSCHEDULE_DAY TD ON (TS.TS_CODE = TD.TS_CODE) LEFT JOIN TRAVELPOINT TP ON(TS.TP_CODE = TP.TP_CODE) WHERE TS.TS_CODE = 'TS1'

// 연관리스트
SELECT TS.TS_CODE, TS.M_CODE, TS.TP_CODE, TS.TS_TITLE, TS.TS_SDAY, TS.TS_THEME, TS.TS_PEOPLE, TS.TS_THUM, TS.TS_DATE, TS.TS_VIEW, M_NAME, TP.CITY_CODE, TP.TP_IMG 
FROM TRAVELSCHEDULE TS 
LEFT JOIN TWTMEMBER M ON (TS.M_CODE = M.M_CODE) 
LEFT JOIN TRAVELPOINT TP ON(TS.TP_CODE = TP.TP_CODE) 
WHERE TS.TS_THEME = '여행테마'
ORDER BY TS_DATE DESC






--------------------------------보미-----------------------------------------


--------------------------------찬우-----------------------------------------



--------------------------------수지-----------------------------------------
SELECT * FROM TRAVELPOINT;
SELECT * FROM CITY;
SELECT * FROM TwTMEMBER;
SELECT * FROM SCHEDULEREVIEW;
--------------------------------철환-----------------------------------------


