SELECT * FROM TravelSchedule;
SELECT * FROM CITY;
--------------------------------용훈-----------------------------------------



--------------------------------범식-----------------------------------------
SELECT * FROM HOTEL;



--------------------------------도영-----------------------------------------

SELECT * FROM TRAVELSCHEDULE;
UPDATE TRAVELSCHEDULE SET M_CODE = 'M3' WHERE M_CODE = 'M2'
SELECT * FROM TRAVELSCHEDULE LEFT JOIN TWTMEMBER USING(M_CODE) ORDER BY TS_CODE DESC;
SELECT * FROM SCHEDULEREVIEW;
SELECT * FROM TRAVELSCHEDULE LEFT JOIN SCHEDULEREVIEW USING(M_CODE) ORDER BY SR_VIEW DESC;
SELECT * FROM TRAVELSCHEDULE LEFT JOIN SCHEDULEREVIEW USING(M_CODE) LEFT JOIN TWTMEMBER USING(M_CODE) ORDER BY TS_DATE DESC;
SELECT * FROM TRAVELSCHEDULE JOIN SCHEDULEREVIEW USING(M_CODE) JOIN TWTMEMBER USING(M_CODE) ORDER BY TS_DATE DESC
SELECT * FROM TRAVELSCHEDULE LEFT JOIN SCHEDULEREVIEW USING(M_CODE) LEFT JOIN TWTMEMBER USING(M_CODE) ORDER BY TS_DATE DESC
UPDATE SCHEDULEREVIEW SET M_CODE = 'M1' WHERE M_CODE IS NULL;
SELECT * FROM TRAVELSCHEDULE LEFT JOIN TWTMEMBER USING(M_CODE) LEFT JOIN TRAVELPOINT USING(TP_CODE)
SELECT * FROM TRAVELPOINT;
SELECT * FROM TRAVELSCHEDULE LEFT JOIN TWTMEMBER USING(M_CODE) LEFT JOIN TRAVELSCHEDULE_DAY USING(TS_CODE) WHERE TS_CODE = 'TS1';
SELECT TS.TS_CODE, TS.M_CODE, TS.TP_CODE, TS.TS_TITLE, TS.TS_SDAY, TS.TS_THEME, TS.TS_PEOPLE, TS.TS_THUM, TS.TS_PERIOD, TS.TS_DATE, TS.TS_VIEW, M.M_ID, TD.TS_DAY, TP.TP_TYPE, TP.TP_CONTENT FROM TRAVELSCHEDULE TS LEFT JOIN TWTMEMBER M ON (TS.M_CODE = M.M_CODE) LEFT JOIN TRAVELSCHEDULE_DAY TD ON (TS.TS_CODE = TD.TS_CODE) LEFT JOIN TRAVELPOINT TP ON(TS.TP_CODE = TP.TP_CODE) WHERE TS.TS_CODE = 'TS1';

SELECT * FROM TRAVELSCHEDULE_DAY;

--------------------------------보미-----------------------------------------


--------------------------------찬우-----------------------------------------



--------------------------------수지-----------------------------------------
SELECT * FROM TRAVELPOINT;
SELECT * FROM CITY;
SELECT * FROM TwTMEMBER;
SELECT * FROM SCHEDULEREVIEW;
--------------------------------철환-----------------------------------------


